#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  techriz-frontend
        bind *:80
        mode http
        default_backend techriz-backend
backend techriz-backend
        balance roundrobin
        server 249811-web-01 100.25.33.113:80 check
        server 249811-web-02 34.229.56.207:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
